config/routes.rb
DemoGloss::Application.routes.draw do
  get "line_items/edit"

  resources :line_items

  resources :carts

  resources :orders

  get "products/show"

  get "products/index"

  get "customers/new"

  get "customers/create"

  get "customers/edit"

  get "customers/update"

  get "customers/delete"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "page/home"

  get "page/about"

  get "page/contact"

  get "page/register"

  get "page/help"

  get "page/services"

  get "demo/index"

    resources :products
    resources :orders do
      resources :customers
    end

       resources :customers
       resource :session

   root :to => 'page#home'

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  #before_filter :authorise

  has_many :line_items, dependent: :destroy

  def authorise
      unless Customer.find_by_id(session[:user_id])
        redirect_to login_url, notice: "Please Log In:-"        
      end    
  end

  def add_product(product_id, quantity)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += quantity
    else
      current_item = line_items.build(product_id: product_id, quantity: quantity)
    end
    current_item
  end

  def update_product(product_id, quantity)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity = quantity
    else
      #throw error - to do
    end
    current_item
  end

  def total_quantity
    line_items.to_a.sum { |item| item.quantity}
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_items
    line_items.count
  end

  def testtotal_price
    total = 0
    line_items.each do |line_item|
      total += line_item.product.unit_price * line_item.quantity
    end
    total
  end
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
  before_filter :authorise_customer
  protect_from_forgery

  def index
      redirect_to root_path, notice: 'Cart EMPTIED'
  end

  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  protected

  def authorise_customer
      unless Customer.find_by_id(session[:user_id])
      # keep customer/visitor on the product page
      # request them to log in in order to make a purchase
      redirect_to :back, notice: "Please log in to purchase"
      end
  end


end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_empty?
     if @cart
    link_to 'View Cart', cart_path(session[:cart_id])
     end

  end
end

app/views/carts/_cart.html.erb


<div>
 <p class="cart_prod">Unique Items:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= cart.total_items %></p>
 <p class="cart_prod">Total Quantity:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= cart.total_quantity %></p>
 <p class="cart_total left">Total Price:&nbsp<%= number_to_currency(cart.total_price, :unit => '&euro;') %></p>
 <p><%= link_to 'View Cart', cart_path(session[:cart_id]) %></p>
  <% if logged_in? %>
 <%= button_to "Checkout", new_order_path, method: :get %>
    <% end %>
</div>



app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div id="content">
  <div id="breadcrumbs">
    <ul>
      <li><a href="#">Home &gt;&gt;</a></li>
      <li><a href="#">Shopping Cart</a></li>

    </ul>
  </div><!--end breadcrumbs-->

  <section class="cartList">
    <header>
      <h1>Shopping Cart</h1>
    </header>
    <div id="backToList">
      <a href="#" title="Continue Shopping">Continue Shopping</a>
    </div><!--end backToList-->
    <div>Summary- Unique Items:<%= @cart.total_items %>&nbsp;&nbsp;&nbsp;Total Quantity:<%= @cart.total_quantity %>&nbsp;&nbsp;&nbsp;Total Price: <%= number_to_currency(@cart.total_price, :unit => '&euro;') %></div>

    <%= render(@cart.line_items) %>

    <%= button_to 'Empty cart', @cart, :method => :delete, :confirm => 'Are you sure?' %>
  </section><!-- end cartList -->
</div><!--end content -->