config/routes.rb
DemoGloss::Application.routes.draw do
  get "line_items/edit"

  resources :line_items

  resources :carts

  resources :orders

  get "products/show"

  get "products/index"

  get "customers/new"

  get "customers/create"

  get "customers/edit"

  get "customers/update"

  get "customers/delete"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "page/home"

  get "page/about"

  get "page/contact"

  get "page/register"

  get "page/help"

  get "page/services"

  get "demo/index"

    resources :products
    resources :orders do
      resources :customers
    end

       resources :customers
       resource :session

   root :to => 'page#home'

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
end

app/views/layouts/_product_nav.html.erb
 <nav>
        <h1>Main Navigation for Products</h1>
        <ul>
          <li><%= link_to "Home", :controller => 'page', :action => 'home' %></li>
          <li><%= link_to "Audio", :controller => 'products', :action => 'index', :category_name => "Audio" %></li>
          <li><%= link_to "TV", :controller => 'products', :action => 'index', :category_name => "TV" %></li>
          <li><%= link_to "PC", :controller => 'products', :action => 'index', :category_name => "PC" %></li>
          <li><%= link_to "Furniture", :controller => 'products', :action => 'index', :category_name => "Furniture" %></li>
        </ul>
 </nav>

app/views/layouts/_search.html.erb

<%= form_tag products_path, :category_name => "Search Results", :method => 'get' do %>
	<p>
		<%= text_field_tag :search_query, params[:search_query] %>
		<%= submit_tag "Search", :description => nil %>
	</p>
<% end %>
<!-- <form action="#" method="get" name="search" id="search">
          <input name="search" type="text" id="search_input" placeholder="search">
          <input name="searchSite" type="submit" id="searchSite" value="go">
 </form> -->

app/views/layouts/_sub_nav.html.erb
 <ul>
        <li><%= link_to "Home", :controller => 'page', :action => 'home' %><span>Welcome to  Cardboard!</span></li>
        <li><%=link_to "About", :controller => 'page', :action => 'about' %><span>Who we are</span></li>
        <li><a href="#">Contact Us</a> <span class="contain">For everything
you want</span></li>
        <li><%= link_to "Register", :controller => 'customers', :action => 'new'  %> <span class="contain">Discover
the advantages</span></li>
        <li><%=  link_to "Help", :controller => 'page', :action => 'help' %> <span>Got Questions?</span></li>
        <li><%= link_to "Our Services", :controller => 'page', :action => 'services' %> <span class="contain">What we have
to offer</span></li>
 </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=  @page_title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body>
<div id="wrapper">
  <div id="header">
    <div class="centerContent">
      <section class="left" id="login">
        <h1>Customer</h1>
        <%= render :partial => "sessions/form"  %>
      </section><!--End #login-->
      <header class="left" id="pageHeading">
        <hgroup>
          <h1>Cardboard </h1>
          <h2>Online Shop </h2>
        </hgroup>
      </header>
      <section class="right" id="cart">
        <h1>Cart</h1>
        <% if @cart %>
        <%= render @cart %>
            <% else %>
        <p style="text-align: right; color: #CBCCC8;">Your Cart is empty</p>
            <% end %>
      </section><!--End #cart-->
    </div><!--End .centerContent-->
  </div><!--End #header-->
  <div class="centerContent bodyContent">
    <div class="clearBoth" id="subNav">
      <!-- Sub Navigation - Home, about etc -->
      <%= render :partial => "layouts/sub_nav.html.erb" %>
    </div><!--End #subNav-->
    <div class="clearLeft" id="navBar">
      <!-- Product Category Navigation -->
      <%= render :partial => "layouts/product_nav.html.erb" %>
      <div class="right" id="search">
        <!-- search box -->
       <%= render :partial => "layouts/search.html.erb" %>
      </div>
    </div><!--End #navBar-->



    <div id="content">
      <% if flash[:notice] %>
          <div id="notice"><%= flash[:notice] %></div>
      <% end %>
      <%=  yield %>                   <!--This is the area that is going to be truly Dynamic ___RUBY ON RAILS GENERATED CONTENT___ -->
    </div><!--End .content -->
  </div><!--End .centerContent-->
  <div class="clearLeft"></div>
</div><!--End #wrapper-->
<div class="centerContent clearLeft ">
  <section class="about">
    <div class="fourAcross">
      <header><h1>About Us</h1></header>

      <h2>Lorem ipsum dolor </h2>
      <p>Sit amet, consectetur adipiscing elit. Integer pellentesque, leo eget commodo iaculis, leo leo consectetur dui, quis pellentesque lectus neque eu orci.</p>

      <p>Vestibulum eleifend nisi diam. <a href="#" class="learn_more">Contact us</a> or Integer pellentesque, leo eget. Phasellus et est vitae .</p>
    </div><!--End FourAcross 1-->
    <div class="fourAcross fontPlace">
      <h2>Shipping Info</h2>
      <p>Phasellus et est vitae lorem posuere congue sed nec quam. <a href="#" class="learn_more">More</a></p>

      <h2>Delivery</h2>
      <p>Aliquam vel tortor a augue fringilla fringilla sit amet ac nunc. Phasellus et est vitae. Sit amet, consectetur adipiscing elit. Integer pellentesque.  <a href="#" class="learn_more">More</a></p>
    </div><!--end FourAcross 2 -->
    <div class="fourAcross fontPlace">
      <h2>Newsletter</h2>
      <p>Sign up to our newsletter!</p>
      <form name="newsLetter" method="post" action="" id="newsLetter">
        <input type="text" name="name" id="news_name">
        <input type="email" name="email" id="news_email">
        <input type="submit" name="submit" id="news_submit" value="Submit">
      </form>
      <div class="followUs">
        <p>Follow Us:</p>
        <a href="#" title=" "> <%= image_tag "rss.jpg", :width => "17", :height => "19", :alt =>" " %></a>
        <a href="#" title=" "><%= image_tag "sv.jpg", :width => "18", :height => "19", :alt =>" " %></a>
        <a href="#" title=" "><%= image_tag "2.jpg", :width => "18", :height => "19", :alt =>" " %></a>
        <a href="#" title=" "><%= image_tag "ic.jpg", :width => "16", :height => "18", :alt =>" " %></a>
        <a href="#" title=" "><%= image_tag "facebook.jpg", :width => "17", :height => "19", :alt =>" " %></a>
        <a href="#" title=" "><%= image_tag "twitter.jpg", :width => "21", :height => "19", :alt =>" " %></a>
      </div><!--end followUs-->
    </div><!--end FourAcross 3 -->
    <div class="fourAcross fontPlace end">
      <h2>Payment Options</h2>
      <div><!--card wrap-around-->
        <a href="#" title="Pay by Visa"><%= image_tag "visa.jpg", :width => "49", :height => "32", :alt =>" Pay by Visa" %></a>
        <a href="#" title="Pay by Visa Electron"><%= image_tag "visa_electrom.jpg", :width => "50", :height => "32", :alt =>" Pay by Visa Electron" %></a>
        <a href="#" title="Pay by American Express"><%= image_tag "american_express.jpg", :width => "49", :height => "32", :alt =>" Pay by American Express" %></a>
        <a href="#" title="Pay by Paypal"><%= image_tag "paypal.jpg", :width => "48", :height => "32", :alt =>" Pay by Paypal" %></a>
      </div><!--end credit card wrap-around-->
      <a href="mailto:lowrygerard@eircom.net" id="contact">Contact Us</a>
      <a href="#" title="Call US" id="call">Call Us 800-111-111</a>
    </div><!--end FourAcross 4 -->
  </section>
  <div class="clearLeft"></div>
</div><!--End .centerContent-->
<div id="footer">
  <footer>
    <div class="centerContent">

      <header><h2>Cardboard Online Shop Internal Links</h2></header>
      <div class="navContainer left">
        <ul>
          <li><a href="#">» Home</a></li>
          <li><a href="#">» Register</a></li>
          <li><a href="#">» Contact Us</a></li>
          <li><a href="#">» Help</a></li>
          <li><a href="#">» Our Services</a></li>
        </ul>

      </div><!--End .navContainer-->
      <div class="navContainer left">
        <ul>
          <li><a href="#">House</a></li>
          <li><a href="#">Accessories</a></li>
          <li><a href="#">Free Time</a></li>
          <li><a href="#">Sport</a></li>
          <li><a href="#">Books</a></li>
          <li><a href="#">Electronics</a></li>
        </ul>
      </div><!--End .navContainer-->
      <div class="navContainer left">
        <ul>
          <li><a href="#">T-shirts</a></li>
          <li><a href="#">Mugs</a></li>
          <li><a href="#">Shirts</a></li>
          <li><a href="#">&nbsp;</a></li>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Shipping and Payment</a></li>
        </ul>
      </div><!--End .navContainer-->
      <div class="navContainer left">
        <h3>Contact Info</h3>
        <address>111 Lorem Ipsu Ave - 01234 Seattle, WA<br />
          T. (111) 111-22333<br />
          F. (111) 111-22333 <br />
          info@cardboardshop.com</address>
      </div><!--End .navContainer-->
      <p class="clearLeft" id="copyRight">&copy; Cardboard Online Store 2011</p>

    </div><!--End .centerContent-->
  </footer>
</div>

</body>
</html>